CREATE TABLE CATEGORIA (
    id BIGINT NOT NULL AUTO_INCREMENT,
    categoria VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUTO (
    id BIGINT NOT NULL AUTO_INCREMENT,
    categoria_id BIGINT NOT NULL,
    produto VARCHAR(100) NOT NULL,
    preco NUMERIC(8,2) NOT NULL,
    quantidade SMALLINT NOT NULL,
    descricao VARCHAR(200) NOT NULL,
    foto VARCHAR(100)
);

CREATE TABLE PEDIDO (
    id BIGINT NOT NULL AUTO_INCREMENT,
    data_pedido DATE NOT NULL,
    cliente_id BIGINT NOT NULL,
    status_pedido VARCHAR(20) NOT NULL,
    sessao varchar(50) NOT NULL
);

CREATE TABLE PEDIDO_ITEM (
    id BIGINT NOT NULL AUTO_INCREMENT,
    pedido_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    quantidade SMALLINT NOT NULL,
    valor NUMERIC(5,2) NOT NULL,
    subtotal NUMERIC(8,2) NOT NULL
);

CREATE TABLE CLIENTE (
    id BIGINT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL,
    rua VARCHAR(100) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    bairro VARCHAR(100) NOT NULL,
    cep VARCHAR(8) NOT NULL,
    estado VARCHAR(2) NOT NULL
);

CREATE TABLE USUARIO (
    id BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT true,
    roles VARCHAR(50) NOT NULL
);